config/routes.rb
Captix::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :event_schedules

   root :to => 'event_schedules#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/event_schedule.rb
class EventSchedule < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/event_schedules_controller.rb
class EventSchedulesController < ApplicationController
  # GET /event_schedules
  # GET /event_schedules.json
  def index
    @event_schedules = EventSchedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_schedules }
    end
  end

  # GET /event_schedules/1
  # GET /event_schedules/1.json
  def show
    @event_schedule = EventSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_schedule }
    end
  end

  # GET /event_schedules/new
  # GET /event_schedules/new.json
  def new
    @event_schedule = EventSchedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_schedule }
    end
  end

  # GET /event_schedules/1/edit
  def edit
    @event_schedule = EventSchedule.find(params[:id])
  end

  # POST /event_schedules
  # POST /event_schedules.json
  def create
    @event_schedule = EventSchedule.new(params[:event_schedule])

    respond_to do |format|
      if @event_schedule.save
        format.html { redirect_to @event_schedule, notice: 'Event schedule was successfully created.' }
        format.json { render json: @event_schedule, status: :created, location: @event_schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @event_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /event_schedules/1
  # PUT /event_schedules/1.json
  def update
    @event_schedule = EventSchedule.find(params[:id])

    respond_to do |format|
      if @event_schedule.update_attributes(params[:event_schedule])
        format.html { redirect_to @event_schedule, notice: 'Event schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_schedules/1
  # DELETE /event_schedules/1.json
  def destroy
    @event_schedule = EventSchedule.find(params[:id])
    @event_schedule.destroy

    respond_to do |format|
      format.html { redirect_to event_schedules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_schedules_helper.rb
module EventSchedulesHelper
end

app/views/event_schedules/_form.html.erb
<%= form_for(@event_schedule) do |f| %>
  <% if @event_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_schedule.errors.count, "error") %> prohibited this event_schedule from being saved:</h2>

      <ul>
      <% @event_schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br />
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :event_time %><br />
    <%= f.text_field :event_time %>
  </div>
  <div class="field">
    <%= f.label :monday %><br />
    <%= f.text_field :monday %>
  </div>
  <div class="field">
    <%= f.label :tuesday %><br />
    <%= f.text_field :tuesday %>
  </div>
  <div class="field">
    <%= f.label :wednsday %><br />
    <%= f.text_field :wednsday %>
  </div>
  <div class="field">
    <%= f.label :thursday %><br />
    <%= f.text_field :thursday %>
  </div>
  <div class="field">
    <%= f.label :friday %><br />
    <%= f.text_field :friday %>
  </div>
  <div class="field">
    <%= f.label :saturday %><br />
    <%= f.text_field :saturday %>
  </div>
  <div class="field">
    <%= f.label :sunday %><br />
    <%= f.text_field :sunday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_schedules/edit.html.erb
<h1>Editing event_schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_schedule %> |
<%= link_to 'Back', event_schedules_path %>

app/views/event_schedules/index.html.erb
<h1></h1>

<table id="table5" align="center">

  <tr>
    <th>Event</th>
    <th>Event date</th>
    <th>Event time</th>
    <th>Monday</th>
    <th>Tuesday</th>
    <th>Wednsday</th>
    <th>Thursday</th>
    <th>Friday</th>
    <th>Saturday</th>
    <th>Sunday</th>
  </tr>

<% @event_schedules.each do |event_schedule| %>
  <tr>
    <td><%= event_schedule.event %></td>
    <td><%= event_schedule.event_date %></td>
    <td><%= event_schedule.event_time %></td>
    <td><%= event_schedule.monday %></td>
    <td><%= event_schedule.tuesday %></td>
    <td><%= event_schedule.wednsday %></td>
    <td><%= event_schedule.thursday %></td>
    <td><%= event_schedule.friday %></td>
    <td><%= event_schedule.saturday %></td>
    <td><%= event_schedule.sunday %></td>

  </tr>
<% end %>

</table>

<br />

app/views/event_schedules/new.html.erb
<h1>New event_schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', event_schedules_path %>

app/views/event_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @event_schedule.event %>
</p>

<p>
  <b>Event date:</b>
  <%= @event_schedule.event_date %>
</p>

<p>
  <b>Event time:</b>
  <%= @event_schedule.event_time %>
</p>

<p>
  <b>Monday:</b>
  <%= @event_schedule.monday %>
</p>

<p>
  <b>Tuesday:</b>
  <%= @event_schedule.tuesday %>
</p>

<p>
  <b>Wednsday:</b>
  <%= @event_schedule.wednsday %>
</p>

<p>
  <b>Thursday:</b>
  <%= @event_schedule.thursday %>
</p>

<p>
  <b>Friday:</b>
  <%= @event_schedule.friday %>
</p>

<p>
  <b>Saturday:</b>
  <%= @event_schedule.saturday %>
</p>

<p>
  <b>Sunday:</b>
  <%= @event_schedule.sunday %>
</p>


<%= link_to 'Edit', edit_event_schedule_path(@event_schedule) %> |
<%= link_to 'Back', event_schedules_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Captix</title>
  <%= stylesheet_link_tag 'formtastic', 'my_formtastic_changes' %>
  <!--[if IE 6]><%= stylesheet_link_tag 'formtastic_ie6' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'formtastic_ie7' %><![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>